version: '3'

services:
  ars2024project:
    image: ars2024project
    build:
      context: .
      dockerfile: ./Dockerfile-multistage
    # koristimo BUILDKIT_INLINE_CACHE za optimizaciju builda, kompresija slika prilokom izgradnje docker image-a
    # args:
    #     - BUILDKIT_INLINE_CACHE=1
    ports:
      - 8000:8000
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500

  consul:
    image: consul:1.15.4
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    volumes:
      - /consul_data:/consul/data
