// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config-groups": {
            "post": {
                "description": "Add a new configuration group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config-groups"
                ],
                "summary": "Add a new configuration group",
                "parameters": [
                    {
                        "description": "Config Group",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ConfigGroup"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Config group successfully added",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config-groups/{name}/{version}": {
            "get": {
                "description": "Get a configuration group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config-groups"
                ],
                "summary": "Get a configuration group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config Group Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Group Version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ConfigGroup"
                        }
                    },
                    "404": {
                        "description": "Config group not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a configuration group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config-groups"
                ],
                "summary": "Remove a configuration group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config Group Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Group Version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Config group successfully removed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Config group not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config-groups/{name}/{version}/configs": {
            "post": {
                "description": "Add a configuration with labels to a group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config-groups"
                ],
                "summary": "Add a configuration with labels to a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config Group Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Group Version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Config with Labels",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ConfigWithLabels"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Config with label successfully added to group",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config-groups/{name}/{version}/configs/{configName}/{configVersion}": {
            "delete": {
                "description": "Remove a configuration from a group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config-groups"
                ],
                "summary": "Remove a configuration from a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config Group Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Group Version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Name",
                        "name": "configName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Version",
                        "name": "configVersion",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Config successfully removed from group",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Config group not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config-groups/{name}/{version}/configs/{labels}/{configName}/{configVersion}": {
            "get": {
                "description": "Search for configurations with labels in a group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config-groups"
                ],
                "summary": "Search for configurations with labels in a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config Group Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Group Version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Labels (key:value;key:value)",
                        "name": "labels",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Name",
                        "name": "configName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Version",
                        "name": "configVersion",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ConfigWithLabels"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid label format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No configs with all labels found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove configurations with labels from a group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config-groups"
                ],
                "summary": "Remove configurations with labels from a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config Group Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Group Version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Labels (key:value;key:value)",
                        "name": "labels",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Name",
                        "name": "configName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Version",
                        "name": "configVersion",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Configs with labels successfully removed from group",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid label format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config-groups/{name}/{version}/{configName}/{configVersion}": {
            "post": {
                "description": "Add a configuration to a group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config-groups"
                ],
                "summary": "Add a configuration to a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config Group Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Group Version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Name",
                        "name": "configName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config Version",
                        "name": "configVersion",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Config successfully added to group",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configs": {
            "post": {
                "description": "Add a new config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Add a new config",
                "parameters": [
                    {
                        "description": "Config object to add",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Config"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Config successfully added",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configs/{name}/{version}": {
            "get": {
                "description": "Get a config by name and version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get a config by name and version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Config"
                        }
                    },
                    "404": {
                        "description": "Config not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a config by name and version",
                "tags": [
                    "config"
                ],
                "summary": "Delete a config by name and version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Config version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Config successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Config not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Config": {
            "description": "A configuration entity with a name, version, and parameters",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "model.ConfigGroup": {
            "description": "A configuration group containing a list of ConfigWithLabels",
            "type": "object",
            "properties": {
                "configs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ConfigWithLabels"
                    }
                },
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "model.ConfigWithLabels": {
            "description": "A configuration with an additional Labels field",
            "type": "object",
            "properties": {
                "labels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Label"
                    }
                },
                "name": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "model.Label": {
            "description": "A key-value pair representing a label",
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Config API",
	Description:      "API for managing configurations",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
